export const mapSVGClassNames = {
  layer: "Map-layer",
  layerId: (id: string) => `Map-layer-id-${id}`,
  area: "Map-area",
  areaId: (id: string) => `Map-area-id-${id}`,
  click: "Map-click",
  clickId: (id: string) => `Map-click-id-${id}`,
  locationTitle: "Map-location-title",
  locationTitleId: (id: string) => `Map-location-title-id-${id}`,
  locationIcon: "Map-location-icon",
  locationIconId: (id: string) => `Map-location-icon-id-${id}`,
  flagId: (id: string) => `Map-flag-id-${id}`,
  flagTransition: "Map-flag-transition",
  flagTransitionId: (id: string) => `Map-flag-transition-id-${id}`,
  flagTransitionForward: "Map-flag-transition-forward",
  flagTransitionBackward: "Map-flag-transition-backward",
  flagTransitionFinished: "Map-flag-transition-finished",
  flagToggle: "Map-flag-toggle",
  flagToggleId: (id: string) => `Map-flag-toggle-id-${id}`,
  foreignObjectText: "Map-foreignObjectText",
  isometric: "Map-isometric",
  isometricTransform: "Map-isometric-transform",
  isometricTransitionFinished: "Map-isometric-transition-finished",
  isometricTransitionHidden: "Map-isometric-transition-hidden",
  active: "Map-active",
  visible: "Map-visible",
  hidden: "Map-hidden",
  empty: "Map-empty",
} as const
