# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

exclude = { glob = ["pnpm-lock.yaml"] }

[[repos]]
repo = "builtin"
hooks = [
    { id = "trailing-whitespace" },
    { id = "end-of-file-fixer" },
    { id = "check-added-large-files" },
    { id = "check-yaml" },
]

[[repos]]
repo = "https://github.com/mirrors-prettier/mirrors-prettier"
rev = "v3.8.4"
hooks = [
    { id = "prettier"}
]
